"""
This family file was auto-generated by generate_family_file.py script.

Configuration parameters:
  url = http://pi4bsdm2.monallabs.in/w/
  name = csvpackdl

Please do not commit this to the Git repository!
"""
from pywikibot import family


class Family(family.Family):  # noqa: D101

    name = 'csvpackdl'
    langs = {
        'en': 'pi4bsdm2.monallabs.in',
    }

    def scriptpath(self, code):
        return {
            'en': '/w',
        }[code]

    def protocol(self, code):
        return {
            'en': 'http',
        }[code]
